### ISSUE TITLE
wait for workflow deletion to complete

### ISSUE THREAD

**Issue by vgunapati** [keikoproj/addon-manager#124]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:

This looks like an edge case in addon manager where if addon workflow already exists from the previous run addon manager will delete and recreate the workflow within the same second. But the main problem is that we are not waiting for workflow delete to complete.

This results in failure when a new workflow pod is submitted, As the old pod is not garbage-collected and marking addon as failure

addon manager code where workflow delete is called https://github.com/keikoproj/addon-manager/blob/05e7852340de68fbf947679cee1cbb475589234e/pkg/workflows/workflow.go#L223

**What you expected to happen**:

wait for workflow deletion to complete before submitting new workflow ( this only happens when you have no changes in the addon and kubectl apply is submitted with the same spec )

**Comment by ccfishk** [comment]
Wait for WF complete is fixed in following changes
 
https://github.com/keikoproj/addon-manager/pull/118/files#diff-9a55e0c3cb87ae6ed9bcb0ff21fdf7a3b1b72dfb5df66f4623675b7878f91749R93-R96

**Comment by ccfishk** [comment]
In the enhancement PR, workflow deletion is handled 
https://github.com/keikoproj/addon-manager/pull/126/files#diff-8dc2338c85abb2ec0a6cb5560fd1aaa3acb0879e5dbb7b04535499668b39b3efR168
