### ISSUE TITLE
Introduce max continuous failure if addon continuous failed

### ISSUE THREAD

**Issue by pzou1974** [keikoproj/addon-manager#17]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE

**What happened**:
current addon mgr continuous retry failed addon and we can't get rid of it unless deleting it.
We should  introduce max continuous failure if addon continuous failed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```

**Comment by imazik** [comment]
@pzou1974 I would like to give this a try.

**Comment by kevdowney** [comment]
Workflows have a timeout and `retryStrategy` that addresses this issue.
