### ISSUE TITLE
Issue during argo upgrade

### ISSUE THREAD

**Issue by pzou1974** [keikoproj/addon-manager#35]
From argoproj 2.3 to 2.4 there are couple config changes.
We need to add in order to make add on working.
https://github.com/argoproj/argo/blob/release-2.4/manifests/install.yaml

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```

**Comment by kevdowney** [comment]
Closed by #36
