### ISSUE TITLE
Support Go Releaser

### ISSUE THREAD

**Issue by kevdowney** [keikoproj/addon-manager#7]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

Use goreleaser to version, build and publish releases.

Follow tutorial https://goreleaser.com/

See our reference [version.go](/keikoproj/addon-manager/blob/master/pkg/version/version.go)

**What happened**:
N/A
**What you expected to happen**:
goreleaser should be used in ci to version the release.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Addon Manager version
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- Addon status:
```
$ kubectl describe addon <addon-name>
```
- controller logs:
```
$ kubectl logs <addon-manager-pod>
```

**Comment by duyngle** [comment]
Hi @kevdowney, in summary, is it we need to execute gorealeaser base on info from version.go

**Comment by kevdowney** [comment]
Hi Duy. We need to add the LDFlags to the build to let version.go have the right vars to display version then use the binary `goreleaser` to do releases in ci.

**Comment by kevdowney** [comment]
Follow Travis integration example. https://goreleaser.com/ci/
